### ISSUE TITLE
I am unable to install this in my Mac having Python3 installed

### ISSUE THREAD

**Issue by barek2k2** [sr-lab/GLITCH#55]
1. git clone git@github.com:sr-lab/GLITCH.git
2. cd GLITCH
3. python -m pip install -e .

Successfully built glitch
Installing collected packages: glitch
  Attempting uninstall: glitch
    Found existing installation: glitch 1.0.1
    Uninstalling glitch-1.0.1:
      Successfully uninstalled glitch-1.0.1
Successfully installed glitch-1.0.1

**Then running the glitch command shows error as of below:**
abdul@Abduls-MacBook-Pro GLITCH % glitch --help             
Traceback (most recent call last):
  File "/Users/abdul/Library/Caches/pypoetry/virtualenvs/glitch-5uPBzSuZ-py3.12/bin/glitch", line 5, in <module>
    from glitch.__main__ import main
  File "/Users/abdul/projects/uwf/GLITCH/glitch/__main__.py", line 15, in <module>
    from glitch.parsers.chef import ChefParser
  File "/Users/abdul/projects/uwf/GLITCH/glitch/parsers/chef.py", line 8, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'

If anybody please helps?

**Comment by Nfsaavedra** [comment]
Hi @barek2k2,

I think there was a missing dependency and that's why that happened. Just commited a hot fix to try to solve your problem.
Please try to `git pull` and re-run `python -m pip install -e .` and report back!

Thanks!

**Comment by barek2k2** [comment]
it works now! thank you so much!

**Comment by barek2k2** [comment]
There are some interesting facts. It works from poetry, but not directly:

```
abdul@Abduls-MacBook-Pro GLITCH % python3 -m pip install -e .
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.
    
    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by Nfsaavedra** [comment]
That's interesting! I've only tested the installation in Linux so I've never had this kind of problems. But that's good to know :) I'll close the issue now! You can re-open it or open a new one if you have any other questions/problems!
