### ISSUE TITLE
Output seems not correct for a simple yaml file

### ISSUE THREAD

**Issue by barek2k2** [sr-lab/GLITCH#56]
Here is my yaml file named `test.yaml` as below:

```
name: create an app with full permission

file:
  path: /app
  owner: foo
  group: foo
  mode: "777"
```

And I ran the command to generate the report this way `glitch --tech ansible --csv test.yaml`

The output below seems not correct:

```
+-------------------------------------+-------------+----------------------------+---------------------------+
| Smell                               | Occurrences | Smell density (Smell/KLoC) | Proportion of scripts (%) |
+-------------------------------------+-------------+----------------------------+---------------------------+
| Admin by default                    |           0 |                        0.0 |                       0.0 |
| Avoid comments                      |           0 |                        0.0 |                       0.0 |
| Duplicate block                     |           0 |                        0.0 |                       0.0 |
| Empty password                      |           0 |                        0.0 |                       0.0 |
| Full permission to the filesystem   |           0 |                        0.0 |                       0.0 |
| Hard-coded password                 |           0 |                        0.0 |                       0.0 |
| Hard-coded secret                   |           0 |                        0.0 |                       0.0 |
| Hard-coded user                     |           0 |                        0.0 |                       0.0 |
| Imperative abstraction              |           0 |                        0.0 |                       0.0 |
| Improper alignment                  |           0 |                        0.0 |                       0.0 |
| Invalid IP address binding          |           0 |                        0.0 |                       0.0 |
| Long Resource                       |           0 |                        0.0 |                       0.0 |
| Long statement                      |           0 |                        0.0 |                       0.0 |
| Misplaced attribute                 |           0 |                        0.0 |                       0.0 |
| Missing default case statement      |           0 |                        0.0 |                       0.0 |
| Multifaceted Abstraction            |           0 |                        0.0 |                       0.0 |
| No integrity check                  |           0 |                        0.0 |                       0.0 |
| Suspicious comment                  |           0 |                        0.0 |                       0.0 |
| Too many variables                  |           0 |                        0.0 |                       0.0 |
| Unguarded variable                  |           0 |                        0.0 |                       0.0 |
| Unnecessary abstraction             |           0 |                        0.0 |                       0.0 |
| Use of HTTP without TLS             |           0 |                        0.0 |                       0.0 |
| Use of obsolete command or function |           0 |                        0.0 |                       0.0 |
| Weak Crypto Algorithm               |           0 |                        0.0 |                       0.0 |
+-------------------------------------+-------------+----------------------------+---------------------------+
| Combined                            |           0 |                        0.0 |                       0.0 |
+-------------------------------------+-------------+----------------------------+---------------------------+
+-----------------+---------------+
| Total IaC files | Lines of Code |
+-----------------+---------------+
|               1 |             7 |
+-----------------+---------------+

```

You see ` Full permission to the filesystem` it should contain occurrences 1. everything shows zero. Did I miss anything? I really appreciate your help.

**Comment by Nfsaavedra** [comment]
Hi @barek2k2!

First of all, I'm not sure the program you provided is a valid Ansible program, I think it should be:

```
---
- name: create an app with full permission
  file:
    path: /app
    owner: foo
    group: foo
    mode: "0775"
```

since a script is either a playbook or a tasks/vars file. If it is a tasks/vars file, I think it needs to be in a YAML list, but correct me if I'm wrong. If I am, then we need to fix it in GLITCH since right now it only supports files in this format.

The next thing is that GLITCH only detects a `Full permission to the filesystem` smell for `0777`. We can argue that `0775` is also dangerous, but allowing all permissions for the group of the file is definitely not as dangerous as for every user. Maybe we should have a configuration to change that. 

For this script, GLITCH has the expected behavior:
```
---
- name: create an app with full permission
  file:
    path: /app
    owner: foo
    group: foo
    mode: "0777"
```

**Comment by barek2k2** [comment]
Thank you for the clarification. I initially used a sample YAML file, but your corrected version for Ansible works perfectly. Could you please provide me a comprehensive sample YAML file that includes all the code smells? It would be very helpful for fully understanding the rules, such as what to write in the YAML file, which key names to use, etc. I really appreciate your kind help.

**Comment by Nfsaavedra** [comment]
No problem! You can find a list of YAML files for each code smell here:
https://github.com/sr-lab/GLITCH/tree/d60f2be9c33a7f3ee13a67717907061f62c399ea/glitch/tests/security/ansible/files
https://github.com/sr-lab/GLITCH/tree/d60f2be9c33a7f3ee13a67717907061f62c399ea/glitch/tests/design/ansible/files

We use these for testing. Similarly, there are samples for the other technologies supported.

Additionally, this work is the result of academic work and there is a paper that describes the rules in GLITCH. At the moment, the paper does not have the rules for all the supported code smells, but it has for some. You can check the Table 3 of the paper, it is a bit formal, but it's good to get an idea of the rules.
https://arxiv.org/pdf/2205.14371.pdf

**Comment by Nfsaavedra** [comment]
You can also check the default configuration of GLITCH:
https://github.com/sr-lab/GLITCH/blob/main/glitch/configs/default.ini
It gives you an idea of the keywords used.

**Comment by barek2k2** [comment]
Awesome! it really helps. I have read your paper, idea is promising! I am also a PhD student and I think I am gonna cite your paper in my upcoming papers :-) Thanks again.
